mantisbt:
  image: littlebookboy/mantisbt:latest
  ports:
    - "80:80"
  links:
    - mysql
  restart: always

mysql:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql